import _ from 'lodash';

var FI = {};
var EN = {};
var SV = {};

_.extend(FI, {
diacor_company_name: 'Diacor ',
diacor_error_404: '404 - Sivua ei löytynyt',
diacor_error_required: 'Pakollinen kenttä',
diacor_filter_extra_city_Espoo: 'Espoo',
diacor_filter_extra_city_Helsinki: 'Helsinki',
diacor_filter_extra_city_Vantaa: 'Vantaa',
diacor_filter_extra_hide: 'Piilota lisävalinnat ',
diacor_filter_extra_label: 'Lisävalinnat',
diacor_filter_extra_label_city: 'Kaupunki',
diacor_filter_extra_label_gender: 'Sukupuoli',
diacor_filter_extra_label_language: 'Kieli',
diacor_filter_extra_show: 'Näytä lisävalinnat ',
diacor_filter_main_reservation_turku_link: 'DIACOR TURUN AJANVARAUS',
diacor_filter_time_day: 'Päivä',
diacor_filter_time_evening: 'Ilta',
diacor_filter_time_morning: 'Aamu',
diacor_header_cancel: 'Varauksen peruuttaminen',
diacor_header_lang_en: 'EN',
diacor_header_lang_fi: 'FI',
diacor_header_lang_se: 'SE',
diacor_header_reservation: 'Ajanvaraus',
diacor_header_summary: 'Kiitos varauksesta!',
diacor_input_placeholder_address: 'Katuosoite',
diacor_input_placeholder_cell: 'Matkapuhelinnumero',
diacor_input_placeholder_city: 'Postitoimipaikka',
diacor_input_placeholder_email: 'Sähköpostiosoite',
diacor_input_placeholder_name: 'Etunimi',
diacor_input_placeholder_name_or_service: 'Nimi tai palvelu',
diacor_input_placeholder_office: 'Toimipiste',
diacor_input_placeholder_phone: 'Puhelinnumero',
diacor_input_placeholder_postalcode: 'Postinumero',
diacor_input_placeholder_reason: 'Kirjoita syy käynnillesi...',
diacor_input_placeholder_reservation_code: 'Varauskoodi',
diacor_input_placeholder_ssn: 'Henkilötunnus',
diacor_input_placeholder_surname: 'Sukunimi',
diacor_ohc_search: ' työterveystiimi',
diacor_ohc_team_list_choose_link: 'Valitse',
diacor_popup_ask_cancel_reservation_confirm_content: 'Voit hallinnoida kaikkia varauksiasi DiacorPlus-palvelussa.',
diacor_popup_ask_cancel_reservation_confirm_header: 'Varauksen tiedot',
diacor_popup_ask_ssn_header: 'Hei, kuka on tulossa vastaanotolle?',
diacor_popup_ask_ssnohc_header: 'Hei työterveysasiakas, aloita ajan varaaminen tästä.',
diacor_popup_button_accept: 'Jatka',
diacor_popup_button_cancel: 'Peruuta',
diacor_popup_button_cancel_appointment: 'Peruuta varaus',
diacor_popup_button_close: 'Sulje',
diacor_popup_button_confirm: 'VAHVISTA VARAUS',
diacor_popup_button_leave_scheduling: 'Poistu ajanvarauksesta',
diacor_popup_button_new_reservation: 'Varaa uusi aika',
diacor_popup_button_return_scheduling: 'Palaa ajanvaraukseen',
diacor_popup_cancel_notfound_headerone: 'Varaustunnuksella ',
diacor_popup_cancel_notfound_headertwo: ' ei löytynyt varausta.',
diacor_popup_cancel_reservation_content: 'Löydät varauskoodin sähköpostistasi varausvahvistuksesta.',
diacor_popup_cancel_reservation_error_header: 'Jotakin meni pieleen varauksen peruuttamisessa.',
diacor_popup_cancel_reservation_header: 'Syötä varauskoodi peruaksesi varaus',
diacor_popup_cancel_reservation_ok_content1: 'Peruutit seuraavan varauksen.',
diacor_popup_cancel_reservation_ok_content2: 'Varauskoodi',
diacor_popup_cancel_reservation_ok_content3: 'Voit hallinnoida kaikkia varauksiasi DiacorPlus-palvelussa.',
diacor_popup_cancel_reservation_ok_header: 'Varaus peruttu',
diacor_popup_creation_error_header: 'Jotakin meni pieleen.',
diacor_popup_doctor_info_languages: 'Asiointikielet',
diacor_popup_doctor_info_locations: 'Toimipisteet',
diacor_popup_doctor_info_not_found: 'Lisätietoja ei valitettavasti löytynyt',
diacor_popup_doctor_info_prices1: 'HINNAT',
diacor_popup_doctor_info_prices2: 'Yksityisasiakkaan hinnat arkisin',
diacor_popup_doctor_info_services: 'Palvelut',
diacor_popup_doctor_info_skills: 'Osaamisalueet',
diacor_popup_forbidden_content: 'Ajan varaaminen internetin kautta on estetty. Voit varata ajan soittamalla numeroon ',
diacor_popup_forbidden_header: 'Ajanvarausta ei voitu tehdä.',
diacor_popup_forbidden_link: '09 7750 7755',
diacor_popup_generic_failure: 'Jotakin meni pieleen, yritä hetken kuluttua uudelleen',
diacor_popup_new_client_header_one: 'Hei, kuka on tulossa vastaanotolle',
diacor_popup_new_client_header_two: 'Uusi asiakas, tervetuloa! Lisää vielä seuraavat tiedot',
diacor_popup_ohc_forbidden_content: 'Voit varata ajan internetin kautta vain yksityiskäyntinä. Varaa työterveyskäynti soittamalla numeroon ',
diacor_popup_ohc_forbidden_header: 'Ajanvarausta ei voitu tehdä.',
diacor_popup_ohc_forbidden_link: '09 7750 7755',
diacor_popup_ohc_notfound_content: 'Henkilötiedoillasi ei löytynyt työterveysasiakkuutta. Tarkista työterveyssopimuksen voimassaolo työnantajaltasi.',
diacor_popup_ohc_notfound_header: 'Hups, jotain meni pieleen.',
diacor_popup_prereservation_error_header: 'Jotakin meni pieleen esivarauksen teossa...',
dialog_popup_prereservation_timeout: 'Esivaraus purettu (tähän joku viksumpi teksti)',
diacor_section_confirmation_content: 'Tarkista tiedot ennen varauksen vahvistamista.',
diacor_section_confirmation_content_contactInfo1: 'LISÄÄ YHTEYSTIETOSI',
diacor_section_confirmation_content_notification: 'Varauksen voi peruuttaa ilmaiseksi 4 tuntia ennen aikaa. Esteen sattuessa peruuta aikasi viimeistään edellisenä päivänä ennen sovittua ajankohtaa. Peruuttamattomasta tai samana päivänä perutusta varauksesta perimme maksun.',
diacor_section_confirmation_content_ohc: 'Työterveyskäynti, ',
diacor_section_confirmation_content_other_payer: 'Muu maksaja (palveluseteli tai työantajan vakuutusyhtiö)',
diacor_section_confirmation_content_payer: 'MAKSAJA',
diacor_section_confirmation_content_plus: 'Ymmärrän, että online vastaanotto onnistuu vain DiacorPlus sovelluksen avulla',
diacor_section_confirmation_content_private: 'Yksityiskäynti',
diacor_section_confirmation_content_reason: 'KÄYNNIN SYY',
diacor_section_confirmation_content_terms: 'Peruutusehdot',
diacor_section_confirmation_content_time: 'VARATTAVA AIKA',
diacor_section_confirmation_header: 'VARAUKSEN VAHVISTAMINEN',
diacor_section_confirmation_note_email: 'Tarvitsemme s-postiosoitteesi vahvistusta varten.',
diacor_section_confirmation_note_ohc: 'Varmista, että palvelu on yrityksesi työterveyspalvelujen piirissä.',
diacor_section_confirmation_note_phone: 'Syötä matkapuhelinnumero muodossa 040-1234567.',
diacor_section_confirmation_note_slot1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_confirmation_note_slot2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_header_hide_link: 'Piilota',
diacor_section_header_show_link: 'Näytä',
diacor_section_header1_desktop: 'Työterveysasiakkaan ajanvaraus',
diacor_section_header1_mobile: 'Työterveysasiakkaat',
diacor_section_header2: 'Omat varaukset',
diacor_section_resource_content: 'Varmista, että palvelu kuuluu yrityksesi työterveys-sopimukseen.',
diacor_section_resource_header: 'TYÖTERVEYSTIIMISI',
diacor_section_summary_add_calendar: 'Lisää kalenteriin',
diacor_section_summary_app: '-sovellus',
diacor_section_summary_button_leave: 'POISTU AJANVARAUKSESTA',
diacor_section_summary_button_new: 'TEE UUSI VARAUS',
diacor_section_summary_content: 'Hienoa! Varaus on vastaanotettu ja olemme lähettäneet sähköpostivarmistuksen osoitteeseesi! Varauksesi tunnus on ',
diacor_section_summary_download: 'Lataa ',
diacor_section_summary_header: 'VARAUKSEN TIEDOT',
diacor_section_summary_notification: 'Saat notifikaation kun lääkäri on valmis ottamaan sinut vastaan.',
diacor_section_summary_open: 'Avaa notifikaation ja DiacorPlus sovellus avataan.',
diacor_section_summary_plus: 'Diacor Plus',
diacor_section_summary_redirect: 'Sinut ohjataan suoraan vastaanotolle.',
diacor_section_summary_reminder_12h: '12h ennen',
diacor_section_summary_reminder_24h: '24h ennen',
diacor_section_summary_reminder_30min: '30 min ennen',
diacor_section_summary_reminder_60min: '60 min ennen',
diacor_section_summary_reminder_choise: 'Valitse milloin haluat muistutuksen tekstiviestillä.',
diacor_section_summary_reminder_order: 'TILAA MUISTUTUS',
diacor_section_summary_reminder_question:'HALUATKO MUISTUTUKSEN?',
diacor_section_summary_reminder_question2: 'MITEN KÄYTÄN DIACOR ONLINE-PALVELUA?',
diacor_section_summary_sure: 'Varmista, että sinulla on puhelin mukana ja että siinä on akkua riittävästi.',
diacor_section_summary_valued_customer: 'ARVOASIAKKUUS',
diacor_section_summary_what: 'Mitäs tähän?',
diacor_section_timesearch_header: 'AJAN VALINTA',
diacor_section_timesearch_header_mobile: 'VALITTU AIKA',
diacor_section_timesearch_link: 'Muuta valintaa',
diacor_time_min: 'min',
diacor_timeslot_diacorplus: 'DiacorPlus Etävastaanotto',
diacor_timeslot_link: 'Varaa',
diacor_timeslot_list_header: 'Vapaat ajat ',
diacor_timeslot_list_no_free_times: 'Halutulle päivälle ei löydy aikoja hakukriteereilläsi. Alla ehdotettuna seuraavia lähimpiä vapaita aikoja. Kalenterissa vihreällä merkityllä päivällä varattavissa olevat ajat.',
diacor_cancel_reservation_not_found1:'Varaustunnuksella ',
diacor_cancel_reservation_not_found2: ' ei löytynyt varausta',
diacor_cancel_reservation_button_leave:'POISTU',
diacor_cancel_reservation_button_confirm:'PERU AIKA',
diacor_cancel_reservation_button_new_reservation:'VARAA UUSI AIKA',
diacor_cancel_reservation_fetching_info:'Haetaan varauken tietoja',
diacor_cancel_reservation_header_info: 'Varauksen tiedot',
diacor_cancel_reservation_header_cancelled:'Varaus peruttu',
diacor_cancel_reservation_header_error: 'Jotakin meni pieleen varauksen perumisessa',
diacor_cancel_reservation_content1:'Peruit seuraavan varauksen',
diacor_cancel_reservation_content1:'Voit hallinnoida kaikkia varauksiasi DiacorPlus-palvelussa',
diacor_cancel_reservation_code:'Varauskoodi:',
diacor_section_summary_reminder_ok1:'Tilaus tallennettu. Saat muistutuksen tekstiviestinä ',
diacor_section_summary_reminder_ok2: ' ennen vastaanottoaikaa.',
diacor_header_turku_link:'Turun ajanvaraus',
});

_.extend(SV, {
diacor_company_name:'Diacor',
diacor_error_404:'404 - Sidan hittades inte',
diacor_error_required:'Obligatoriskt fält',
diacor_filter_extra_city_Espoo:'Esbo',
diacor_filter_extra_city_Helsinki:'Helsingfors',
diacor_filter_extra_city_Vantaa:'Vanda',
diacor_filter_extra_hide:'Göm tilläggsval',
diacor_filter_extra_label:'Tilläggsval',
diacor_filter_extra_label_city:'Stad',
diacor_filter_extra_label_gender:'Kön',
diacor_filter_extra_label_language:'Språk',
diacor_filter_extra_show:'Visa tilläggsval',
diacor_filter_main_reservation_turku_link:'DIACOR ÅBO TIDSBOKNING',
diacor_filter_time_day:'Dag',
diacor_filter_time_evening:'Kväll',
diacor_filter_time_morning:'Morgon',
diacor_header_cancel:'Avbokning',
diacor_header_lang_en:'EN',
diacor_header_lang_fi:'FI',
diacor_header_lang_se:'SE',
diacor_header_reservation:'Tidsbokning',
diacor_header_summary:'Tack för reservationen!',
diacor_input_placeholder_address:'Gatuadress',
diacor_input_placeholder_cell:'Mobiltelefonnummer',
diacor_input_placeholder_city:'Postanstalt',
diacor_input_placeholder_email:'E-post adress',
diacor_input_placeholder_name:'Förnamn',
diacor_input_placeholder_name_or_service:'Namn eller tjänst',
diacor_input_placeholder_office:'Läkarstation',
diacor_input_placeholder_phone:'Telefonnummer',
diacor_input_placeholder_postalcode:'Postnummer',
diacor_input_placeholder_reason:'Beskriv orsaken till besöket…',
diacor_input_placeholder_reservation_code:'Bokningskoden',
diacor_input_placeholder_ssn:'Personbeteckning',
diacor_input_placeholder_surname:'Efternamn',
diacor_ohc_search:' företagshälsovård',
diacor_ohc_team_list_choose_link:'Välj',
diacor_popup_ask_cancel_reservation_confirm_content:'Ni kan administrera alla era bokningar i DiacorPlus applikationen. ',
diacor_popup_ask_cancel_reservation_confirm_header:'Tidsbokningen',
diacor_popup_ask_ssn_header:'Hej! För vem bokas tiden?',
diacor_popup_ask_ssnohc_header:'Hej företagshälsovårdskund! Vänligen börja tidsbokningen här.',
diacor_popup_button_accept:'Fortsätt',
diacor_popup_button_cancel:'Ångra',
diacor_popup_button_cancel_appointment:'Avboka din tidsbokning',
diacor_popup_button_close:'Stäng',
diacor_popup_button_confirm:'BEKRÄFTA BOKNINGEN',
diacor_popup_button_leave_scheduling:'Lämna tidsbokningen',
diacor_popup_button_new_reservation:'Boka en ny tid',
diacor_popup_button_return_scheduling:'Återvänd till tidsbokningen',
diacor_popup_cancel_notfound_headerone:'På bokningsnumret ',
diacor_popup_cancel_notfound_headertwo:' hittades inga bokningar.',
diacor_popup_cancel_reservation_content:'Ni hittar bokningskoden i e-postmeddelandet om er tidsbokning.',
diacor_popup_cancel_reservation_error_header:'Nånting gick fel vid avbokningen.',
diacor_popup_cancel_reservation_header:'Ge bokningskoden för att avboka',
diacor_popup_cancel_reservation_ok_content1:'Ni avbokade denna bokning.',
diacor_popup_cancel_reservation_ok_content2:'Bokningskoden',
diacor_popup_cancel_reservation_ok_content3:'Ni kan administrera alla era bokningar i DiacorPlus applikationen. ',
diacor_popup_cancel_reservation_ok_header:'Avbokningen gjord',
diacor_popup_creation_error_header:'Nånting gick fel.',
diacor_popup_doctor_info_languages:'Språkkunskaper',
diacor_popup_doctor_info_locations:'Läkarstation',
diacor_popup_doctor_info_not_found:'Tyvärr hittades ingen tillägsinformation.',
diacor_popup_doctor_info_prices1:'PRISET',
diacor_popup_doctor_info_prices2:'Pris för privatpersoner vardagar',
diacor_popup_doctor_info_services:'Tjänster',
diacor_popup_doctor_info_skills:'Kunnande',
diacor_popup_forbidden_content:'Tidsboking via internet är blockerat. Vänligen boka tid genom att ringa numret ',
diacor_popup_forbidden_header:'Tidsbokningen kunde int göras.',
diacor_popup_forbidden_link:'09 7750 7755',
diacor_popup_generic_failure:'Nånting gick fel, försök pånytt on en stund.',
diacor_popup_new_client_header_one:'Hej vem är tidsbokningen för',
diacor_popup_new_client_header_two:'Ny kund, välkommen! Vänligen tillägg följande information',
diacor_popup_ohc_forbidden_content:'Ni kan endast boka tid till privatpesök via nätet.  För att boka tid till företagshälsovården bör ni ringa numret ',
diacor_popup_ohc_forbidden_header:'Tidsbokningen kunde inte slutföras.',
diacor_popup_ohc_forbidden_link:'09 7750 7755',
diacor_popup_ohc_notfound_content:'Inget kontrakt för företagshälsovård hittades på er personbeteckning. Vänligen kontrollera att kontraktet är i kraft.',
diacor_popup_ohc_notfound_header:'Ops, nånting gick fel.',
diacor_popup_prereservation_error_header:'Nånting gick fel med den preliminärä bokingen…',
diacor_section_confirmation_content:'Kontrollera bokningen före bekräftan',
diacor_section_confirmation_content_contactInfo1:'KONTAKTUPPGIFTER',
diacor_section_confirmation_content_notification:'Avbokning kan göras kostnadsfritt senast 4 timmar innan bokningen börjar. Efter det är ni tvungna att betala fullt pris även om ni inte anländer till besöket.',
diacor_section_confirmation_content_ohc:'Företagshälsovård',
diacor_section_confirmation_content_other_payer:'Annan betalare (försäkringsbolag eller betalningsförbindelse)',
diacor_section_confirmation_content_payer:'BETALARE',
diacor_section_confirmation_content_plus:'Jag godkänner att online mottagning endast kan genomföras via DiacorPlus applikationen',
diacor_section_confirmation_content_private:'Privat besök',
diacor_section_confirmation_content_reason:'ORSAK TILL BESÖKET',
diacor_section_confirmation_content_terms:'Avbokningsregler',
diacor_section_confirmation_content_time:'BOKNINGEN',
diacor_section_confirmation_header:'BEKRÄFTA BOKNINGEN',
diacor_section_confirmation_note_email:'Företagshälsovårdens tidsbokning',
diacor_section_confirmation_note_ohc:'Vänligen kontrollera, att tjänsten hör till din företagshälsovård.',
diacor_section_confirmation_note_phone:'Ge telefonnumret i formatet 040-1234567.',
diacor_section_confirmation_note_slot1:' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_confirmation_note_slot2:' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_header_hide_link:'Göm',
diacor_section_header_show_link:'Visa',
diacor_section_header1_desktop:'Företagshälsovårdens tidsbokning',
diacor_section_header1_mobile:'Företagshälsovård',
diacor_section_header2:'Mina reservationer',
diacor_section_resource_content:'Försäkra dig om att tjänsten ingår i din företagshälsovård.',
diacor_section_resource_header:'DITT FÖRETAGSHÄLSOVÅRD TEAM',
diacor_section_summary_add_calendar:'För till kalender',
diacor_section_summary_app:' applikationen',
diacor_section_summary_button_leave:'LÄMNA TIDSBOKNINGEN',
diacor_section_summary_button_new:'GÖR EN NY TIDSBOKNING',
diacor_section_summary_content:'Toppen! Tidsbokningen är gjord och en bekräfta på bokningen har skickats till er e-post. Bokningskoden är',
diacor_section_summary_download:'Ladda ner',
diacor_section_summary_header:'TIDSBOKNINGEN',
diacor_section_summary_notification:'Du får en notifiering när läkaren kan ta emot dig.',
diacor_section_summary_open:'Öppna notifieringen och DiacorPlus applikationen öppnas.',
diacor_section_summary_plus:'DiacorPlus',
diacor_section_summary_redirect:'Du styrs direkt till mottagningen.',
diacor_section_summary_reminder_12h:'24h innan',
diacor_section_summary_reminder_24h:'2h innan',
diacor_section_summary_reminder_30min:'30 min innan',
diacor_section_summary_reminder_60min:'60 min innan',
diacor_section_summary_reminder_choise:'Välj när vill du få en påminnelse.',
diacor_section_summary_reminder_order:'BESTÄLL PÅMINNELSE',
diacor_section_summary_reminder_question:'BESTÄLL PÅMINNELSE?',
diacor_section_summary_reminder_question2:'HUR ANVÄNDER JAG DIACOR ONLINE TJÄNSTEN?',
diacor_section_summary_sure:'Försäkra dig om att du har telefonen tillhanda och att du har tillräckligt med laddning i batteriet.',
diacor_section_summary_valued_customer:'VÄRDEKUND',
diacor_section_summary_what:'Sammandrag',
diacor_section_timesearch_header:'VÄLJ TIDPUNKT',
diacor_section_timesearch_link:'Ändra tidpunkt',
diacor_time_min:'min',
diacor_timeslot_diacorplus:'DiacorPlus mottagning',
diacor_timeslot_link:'Boka',
diacor_timeslot_list_header:'Lediga tider ',
diacor_timeslot_list_no_free_times:'Inga lediga tider med givna kriterier hittades. Nedan närmaste följande tider. I kalendern brevid visas med grönt dagarna med lediga tider.',
diacor_cancel_reservation_not_found1:'På bokningsnumret ',
diacor_cancel_reservation_not_found2:' hittades inga bokningar.',
diacor_cancel_reservation_button_leave:'STÄNG',
diacor_cancel_reservation_button_confirm:'AVBOKA',
diacor_cancel_reservation_button_new_reservation:'BOKA NY TID',
diacor_cancel_reservation_fetching_info:'Hämtar bokningens information',
diacor_cancel_reservation_header_info:'Tidsbokningen',
diacor_cancel_reservation_header_cancelled:'Avbokningen gjord',
diacor_cancel_reservation_header_error:'Nånting gick fel vid avbokningen.',
diacor_cancel_reservation_content1:'Följande tid avbokades',
diacor_cancel_reservation_content1:'Ni kan administrera alla bokningar i DiacorPlus applikationen. ',
diacor_cancel_reservation_code:'Bokningskoden',
diacor_section_summary_reminder_ok1:'Påminnelsen beställd. Du får en sms som påminnelse ',
diacor_section_summary_reminder_ok2:' innan bokningen.',
diacor_header_turku_link:'Åbo tidsbokning',

});

 _.extend(EN, {
diacor_company_name:'Diacor',
diacor_error_404:'404 - Page not found',
diacor_error_required:'Required field',
diacor_filter_extra_city_Espoo:'Espoo',
diacor_filter_extra_city_Helsinki:'Helsinki',
diacor_filter_extra_city_Vantaa:'Vantaa',
diacor_filter_extra_hide:'Hide additional search criterias',
diacor_filter_extra_label:'Additional search criterias',
diacor_filter_extra_label_city:'City',
diacor_filter_extra_label_gender:'Gender',
diacor_filter_extra_label_language:'Language',
diacor_filter_extra_show:'Show additional search criterias',
diacor_filter_main_reservation_turku_link:'DIACOR TURKU TIMEBOOKING',
diacor_filter_time_day:'Day',
diacor_filter_time_evening:'Evening',
diacor_filter_time_morning:'Morning',
diacor_header_cancel:'Cancel reservation',
diacor_header_lang_en:'ENG',
diacor_header_lang_fi:'FIN',
diacor_header_lang_se:'SWE',
diacor_header_reservation:'Time booking',
diacor_header_summary:'Thank you for the reservation!',
diacor_input_placeholder_address:'Street adress',
diacor_input_placeholder_cell:'Mobile phone',
diacor_input_placeholder_city:'City',
diacor_input_placeholder_email:'E-mail adress',
diacor_input_placeholder_name:'Firstname',
diacor_input_placeholder_name_or_service:'Name or service',
diacor_input_placeholder_office:'Medical centre',
diacor_input_placeholder_phone:'Phone number',
diacor_input_placeholder_postalcode:'Postal code',
diacor_input_placeholder_reason:'Reason for appointment…',
diacor_input_placeholder_reservation_code:'Reservation code',
diacor_input_placeholder_ssn:'Personal identity code',
diacor_input_placeholder_surname:'Surname',
diacor_ohc_search:' occupational healthcare team',
diacor_ohc_team_list_choose_link:'Choose',
diacor_popup_ask_cancel_reservation_confirm_content:'You can administer all your reservations in the DiacorPlus application.',
diacor_popup_ask_cancel_reservation_confirm_header:'Reservation details',
diacor_popup_ask_ssn_header:'Hi! Who is the booking for?',
diacor_popup_ask_ssnohc_header:'Hi occupational healthcare customer. Please start you timebooking here.',
diacor_popup_button_accept:'Accept',
diacor_popup_button_cancel:'Cancel',
diacor_popup_button_cancel_appointment:'Cancel your appointment',
diacor_popup_button_close:'Close',
diacor_popup_button_confirm:'CONFIRM RESERVATION',
diacor_popup_button_leave_scheduling:'Leave timebooking',
diacor_popup_button_new_reservation:'Make a new reservation',
diacor_popup_button_return_scheduling:'Return to timebooking',
diacor_popup_cancel_notfound_headerone:'On the bookingnumber ',
diacor_popup_cancel_notfound_headertwo:' there were no reservations found.',
diacor_popup_cancel_reservation_content:'You can find the reservation code in the booking confirmation e-mail.',
diacor_popup_cancel_reservation_error_header:'Something went wrong when cancelling the reservation.',
diacor_popup_cancel_reservation_header:'Give the reservation code to cancel the reservation',
diacor_popup_cancel_reservation_ok_content1:'You cancelled the following reservation.',
diacor_popup_cancel_reservation_ok_content2:'Reservation code',
diacor_popup_cancel_reservation_ok_content3:'You can administer all your reservations in the DiacorPlus application.',
diacor_popup_cancel_reservation_ok_header:'Reservation has been cancelled',
diacor_popup_creation_error_header:'Something went wrong. Please try again in a minute.',
diacor_popup_doctor_info_languages:'Langages',
diacor_popup_doctor_info_locations:'Medical centre',
diacor_popup_doctor_info_not_found:'Unfortunately no additional information was found.',
diacor_popup_doctor_info_prices1:'PRICES',
diacor_popup_doctor_info_prices2:'Price for private customer duting weekdays',
diacor_popup_doctor_info_services:'Services',
diacor_popup_doctor_info_skills:'Areas of knowledge',
diacor_popup_forbidden_content:'Timebooking via internet is blocked. Please book by calling the number ',
diacor_popup_forbidden_header:'The timebooking could not be made.',
diacor_popup_forbidden_link:'09 7750 7755',
diacor_popup_generic_failure:'Something went wrong. Please try again in a minute.',
diacor_popup_new_client_header_one:'Hi who is the reservation for',
diacor_popup_new_client_header_two:'New customer, welcome! ',
diacor_popup_ohc_forbidden_content:'',
diacor_popup_ohc_forbidden_header:'The reservation could not be made.',
diacor_popup_ohc_forbidden_link:'09 7750 7755',
diacor_popup_ohc_notfound_content:'No occupational healthcare agreement was found on you personal identity code. Please check the validity.',
diacor_popup_ohc_notfound_header:'Oops, something went wrong.',
diacor_popup_prereservation_error_header:'Something went wrong with making the prereservation…',
diacor_section_confirmation_content:'Please check the reservation details before confirmation',
diacor_section_confirmation_content_contactInfo1:'CONTACT DETAILS',
diacor_section_confirmation_content_notification:'The reservation cancellation can be done free of charge latest 4 hours before the reservation. After that you are obliged to pay for the appointment even if you can´t attend.',
diacor_section_confirmation_content_ohc:'Occupational healthcare',
diacor_section_confirmation_content_other_payer:'Other payer (ie. insurance company)',
diacor_section_confirmation_content_payer:'PAYER',
diacor_section_confirmation_content_plus:'I accept that an online appointment only can be carried out via the DiacorPlus application',
diacor_section_confirmation_content_private:'Private appointment',
diacor_section_confirmation_content_reason:'REASON FOR RESERVATION',
diacor_section_confirmation_content_terms:'Cancellation policy',
diacor_section_confirmation_content_time:'THE RESERVATION',
diacor_section_confirmation_header:'CONFIRM RESERTAVTION',
diacor_section_confirmation_note_email:'Occupational healthcare timebooking',
diacor_section_confirmation_note_ohc:'Please check that the service is included in your occupational healthcare agreement.',
diacor_section_confirmation_note_phone:'Please give your phone number in the format 040-1234567.',
diacor_section_confirmation_note_slot1:' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_confirmation_note_slot2:' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ornare dui.',
diacor_section_header_hide_link:'Hide',
diacor_section_header_show_link:'Show',
diacor_section_header1_desktop:'Occupational healthcare timebooking',
diacor_section_header1_mobile:'Occupational healthcare',
diacor_section_header2:'Own reservations',
diacor_section_resource_content:'Make sure the service is included in you occupational healthcare.',
diacor_section_resource_header:'YOUR OCCUPATIONAL HEALTHCARE TEAM',
diacor_section_summary_add_calendar:'Add to calendar',
diacor_section_summary_app:' application',
diacor_section_summary_button_leave:'LEAVE TIMEBOOKING',
diacor_section_summary_button_new:'MAKE A NEW RESERVATION',
diacor_section_summary_content:'Great! The reservation has been completed and a confirmation has been sent to you e-mail. The reservation code is',
diacor_section_summary_download:'Download',
diacor_section_summary_header:'RESERVATION DETAILS',
diacor_section_summary_notification:'You will recieve a notification when the doctor can see you.',
diacor_section_summary_open:'Open the notification and DiacorPlus application will open.',
diacor_section_summary_plus:'DiacorPlus',
diacor_section_summary_redirect:'You will be redirected to the appointment.',
diacor_section_summary_reminder_12h:'24h before',
diacor_section_summary_reminder_24h:'2h before',
diacor_section_summary_reminder_30min:'30 min before',
diacor_section_summary_reminder_60min:'30 min before',
diacor_section_summary_reminder_choise:'Choose when you would like to have a reminder.',
diacor_section_summary_reminder_order:'ORDER A REMINDER',
diacor_section_summary_reminder_question:'ORDER A REMINDER?',
diacor_section_summary_reminder_question2:'HOW TO USE THE DIACOR ONLINE SERVICE?',
diacor_section_summary_sure:'Make sure you have your phone at hand and that it has a charged battery.',
diacor_section_summary_valued_customer:'VALUECUSTOMER',
diacor_section_summary_what:'Summary',
diacor_section_timesearch_header:'CHOOSE A DATE',
diacor_section_timesearch_link:'Change the date',
diacor_time_min:'min',
diacor_timeslot_diacorplus:'DiacorPlus appointment',
diacor_timeslot_link:'Reserve',
diacor_timeslot_list_header:'Available times ',
diacor_timeslot_list_no_free_times:'No availabul times with given crieterias was found. Below next availabul times. In the calendar below availabul days are highlighed with green color.',
diacor_cancel_reservation_not_found1:'On the bookingnumber ',
diacor_cancel_reservation_not_found2:' there were no reservations found.',
diacor_cancel_reservation_button_leave:'CLOSE',
diacor_cancel_reservation_button_confirm:'CANCEL RESERVATION',
diacor_cancel_reservation_button_new_reservation:'MAKE A NEW RESERVATION',
diacor_cancel_reservation_fetching_info:'Fetching booking information',
diacor_cancel_reservation_header_info:'Reservation details',
diacor_cancel_reservation_header_cancelled:'Cancellation done',
diacor_cancel_reservation_header_error:'Something went wrong when cancelling the reservation.',
diacor_cancel_reservation_content1:'The following booking was cancelled',
diacor_cancel_reservation_content1:'You can administer all your reservations in the DiacorPlus application.',
diacor_cancel_reservation_code:'Reservation code',
diacor_section_summary_reminder_ok1:'Reminder has been set. You will recieve a message ',
diacor_section_summary_reminder_ok2:' before the booking.',
diacor_header_turku_link:'Turku timebooking',
 });

 export default function text(key) {

    if(window.T === 'fi') {
        return FI[key] || key;
    }
    else if (window.T === 'sv') {
        return SV[key] || key;
    }
    else if (window.T === 'en') {
        return EN[key] || key;
    }
    else {
        return FI[key] || key;
    }
 };
